
###
# 1: Mostrar su código IDAT y su nombre en el siguiente formato: CÓDIGO - NOMBRE
GET https://rest-ec2-garcia-tito.onrender.com

###
# 2: Mostrar su código IDAT
GET https://rest-ec2-garcia-tito.onrender.com/idat/codigo

###
# 3: Mostrar su nombre completo
GET https://rest-ec2-garcia-tito.onrender.com/idat/nombre-completo

##############################################
#         Requests CON base de datos         #
##############################################
# Tabla: cursos:                             #
#   - id: int (strategy=GenerationType.AUTO) #
#   - nombre: string                         #
#   - creditos: int                          #
##############################################


###
# 4: Listar cursos
GET https://rest-ec2-garcia-tito.onrender.com/api/curso/listar HTTP/1.1

###
# 5: Nuevo Curso
POST https://rest-ec2-garcia-tito.onrender.com/api/curso/nuevo HTTP/1.1
Content-Type: application/x-www-form-urlencoded

nombre=DSW6
&creditos=4

###
# 6: Eliminar Curso
DELETE https://rest-ec2-garcia-tito.onrender.com/api/curso/eliminar
Content-Type: application/x-www-form-urlencoded

id=52

###

DELETE https://reynaldogarciatito-bug-free-memory-4x99j5wv969hj9w5-8080.preview.app.github.dev/api/curso/eliminar
Content-Type: application/x-www-form-urlencoded

id=52