@server = https://reynaldogarciatito-bug-free-memory-4x99j5wv969hj9w5-8080.preview.app.github.dev

###
GET {{server}}

###
GET {{server}}/cursos

###
GET {{server}}/cursos?size=3

###
GET {{server}}/cursos?size=2&page=1

###
GET {{server}}/cursos?sort=creditos,desc

###
GET {{server}}/cursos?size=2&page=1&sort=creditos,desc

###
GET {{server}}/cursos/102

### 
POST {{server}}/cursos
Content-Type: application/json

{"nombre": "Algoritmos", "creditos": 3}

### 
PATCH {{server}}/cursos/102
Content-Type: application/json

{"creditos": 4}

###

DELETE {{server}}/cursos/102

###
GET {{server}}/cursos/search/findByNombre?nombre=Algoritmos
###
GET {{server}}/cursos
###
GET {{server}}/profile/cursos
###
GET {{server}}/cursos/search
###










###
POST {{server}}/users
Content-Type: application/json

{"nombre": "Compiladores", "creditos": 5}