@server = https://reynaldogarciatito-bug-free-memory-4x99j5wv969hj9w5-8080.preview.app.github.dev

//@server = https://rest-ec2-garcia-tito.onrender.com

###
GET {{server}}

###
GET {{server}}/cursos

###
GET {{server}}/cursos?size=3

###
GET {{server}}/cursos?size=2&page=1

###
GET {{server}}/cursos?sort=creditos,desc

###
GET {{server}}/cursos?size=2&page=1&sort=creditos,desc

###
GET {{server}}/cursos/102

### 
POST {{server}}/cursos
Content-Type: application/json

{"nombre": "Matematicas", "creditos": 2, "id_carrera": 1}

### 
PATCH {{server}}/cursos/102
Content-Type: application/json

{"creditos": 4}

###

DELETE {{server}}/cursos/102

###
GET {{server}}/cursos/search/findByNombre?nombre=Algoritmos
###
GET {{server}}/cursos/1
###
GET {{server}}/profile/cursos
###
GET {{server}}/cursos/search
###




#################


GET {{server}}/carreras
###
GET {{server}}/carreras/1/cursos
###
POST {{server}}/carreras
Content-Type: application/json

{"nombre": "Desarrollo de Sistemas de Informacion"}

### 
PATCH {{server}}/cursos/4
Content-Type: application/json

{"id_carrera": 2}

###

GET {{server}}/cursos/4/carrera